// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf Java Version: 4.33.2

package com.xiaozhi.study.serialization.protobuf;

@com.google.protobuf.Generated
public final class TestProto extends com.google.protobuf.GeneratedFile {
  private TestProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "TestProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiaozhi_demo_netty_part2_protobuf_Test_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xiaozhi_demo_netty_part2_protobuf_Test_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ntest.proto\022%com.xiaozhi.demo.netty.par" +
      "t2.protobuf\"!\n\004Test\022\014\n\004name\030\001 \001(\t\022\013\n\003age" +
      "\030\002 \001(\005B7\n%com.xiaozhi.demo.netty.part2.p" +
      "rotobufB\tTestProtoP\001\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_xiaozhi_demo_netty_part2_protobuf_Test_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_xiaozhi_demo_netty_part2_protobuf_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_xiaozhi_demo_netty_part2_protobuf_Test_descriptor,
        new String[] { "Name", "Age", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
